### ISSUE TITLE
Will it support PlainTasks package in the Sublime?

### ISSUE THREAD

**Issue by JimmyLv** [robwalton/alfred-taskpaper-workflow#3]
ref: https://github.com/aziz/PlainTasks

**Comment by robwalton** [comment]
I'm afraid not. It depends on the TaskPaper API.

The file reading/writing part of this is open source: https://github.com/jessegrosjean/birch-outline; but control over the application itself is bespoke. It would be possible in principle to keep the user interface of the workflow and replace just the Apple javascript code with something that talks to Sublime.
