### ISSUE TITLE
Fix workflow data folder to work with Alfred 4(+)

### ISSUE THREAD

**Issue by jduprey** [robwalton/alfred-taskpaper-workflow#7]
After installation of 1.0 alfred-taskpaper-workflow and selecting the document it did not seem to work.

When I debugged it, the debug logs were reporting a missing folder..

I created the folder then all worked:

```
$ mkdir -p "~/Library/Application Support/Alfred 3/Workflow Data/com.github.robwalton.taskpaper-alfred-workflow"
```

It'd be nice if it would tell TaskPaper to save the doc after editing it!

**Comment by robwalton** [comment]
Thanks for the report. It's a duplicate of #5 so am closing this ticket.

> It'd be nice if it would tell TaskPaper to save the doc after editing it!

Seems sensible, I've created #8 .
